name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports: ["6379:6379"]
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      REDIS_URL: redis://localhost:6379/0
      BASE_URL: http://localhost:8000

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check .
          black --check .

      - name: Start API (background)
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 2

      - name: Run tests
        run: |
          pytest -q
